# fly.toml app configuration file generated for jeddit on 2023-08-06T20:43:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jeddit"
primary_region = "gru"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  REDIRECT_URI = "https://jeddit.fly.dev/auth"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
